### ISSUE TITLE
couldn't find file 'es6-module-loader/dist/es6-module-loader'

### ISSUE THREAD

**Issue by thewatts** [nfm/rails-es6-modules#1]
Found this repo from here: https://github.com/josh/sprockets-es6/issues/6#issuecomment-94104058

Cloned it, bundled, and started it - and I'm getting this error:
`couldn't find file 'es6-module-loader/dist/es6-module-loader'`

Here's a screenshot:
![screen shot 2015-04-25 at 12 38 26 am](https://cloud.githubusercontent.com/assets/1141717/7331755/a265ee18-eae3-11e4-9a2e-42f3d18b86d7.png)

Looks like I'm missing something?

**Comment by nfm** [comment]
Hey @thewatts, sorry, just threw this together to play around with so I haven't documented it at all.

I've used bower to manage those dependencies in 56db30a8fe02105b17aa419c5bdce8dcbf00fe12, so you'll need to install the components using `bower install`. Alternatively, you could just grab static copies of those files from the appropriate sources, copy them into `vendor/assets/javascripts`, and change the files required from `application.es6` to match the file names that you've copied into vendor.

**Comment by thewatts** [comment]
Ahh, makes sense :)

No worries!

Thanks for the quick reply!
